export interface LanguageOption {
  code: 'en' | 'uz' | 'ru' | 'es' | 'de';
  name: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English' },
  { code: 'uz', name: 'O‘zbekcha' },
  { code: 'ru', name: 'Русский' },
  { code: 'es', name: 'Español' },
  { code: 'de', name: 'Deutsch' },
];

export const VALID_LANG_CODES = ['en', 'uz', 'ru', 'es', 'de'];

export function getLangCodeFromUrl(): 'en' | 'uz' | 'ru' | 'es' | 'de' {
  if (typeof window === 'undefined') return 'en';
  const pathname = window.location.pathname.toLowerCase();
  const segment = pathname.split('/').filter(Boolean)[0];
  if (segment && VALID_LANG_CODES.includes(segment)) {
    return segment as 'en' | 'uz' | 'ru' | 'es' | 'de';
  }
  return 'en';
}

export function syncUrlForLang(code: string, replace = false) {
  if (typeof window === 'undefined') return;
  const targetPath = `/${code}${window.location.search}`;
  if (window.location.pathname !== `/${code}`) {
    if (replace) {
      window.history.replaceState({}, '', targetPath);
    } else {
      window.history.pushState({}, '', targetPath);
    }
  }
}

export function getLangNameFromCode(code: string): string {
  const found = LANGUAGES.find((l) => l.code === code);
  return found ? found.name : 'English';
}

export function getLangCodeFromName(name: string): 'en' | 'uz' | 'ru' | 'es' | 'de' {
  const found = LANGUAGES.find(
    (l) => l.name === name || l.code === name.toLowerCase() || (name.includes('bek') && l.code === 'uz')
  );
  return found ? (found.code as any) : 'en';
}

export const TRANSLATIONS = {
  en: {
    watchSmarter1: "Watch ",
    watchSmarter2: "Smarter.",
    learnFaster1: "Learn ",
    learnFaster2: "Faster.",
    subtitle: "Discover amazing videos, live streams and courses. Personalized for you with the power of AI.",
    aiRec: "AI Recommendation",
    basedOnHistory: "Based on watch history",
    continueLearning: "Continue Learning",
    yourProgress: "Your Progress",
    thisWeek: "This Week",
    streak: "Streak",
    keepItUp: "Keep it up!",
    days: "Days",
    protectedDataTitle: "Protected Data",
    protectedDataDesc: "Your data is always protected",
    smartSuggestionsTitle: "Smart Suggestions",
    smartSuggestionsDesc: "Smarter recommendations for you",
    anyDeviceTitle: "Any Device",
    anyDeviceDesc: "Access content on any device",
    welcomeBack: "Welcome Back 👋",
    createAccountHeader: "Create Account 🚀",
    signInSub: "Sign in to continue your SoftView journey",
    signUpSub: "Sign up to start your SoftView journey",
    fullName: "Full Name",
    emailOrUsername: "Email or Username",
    password: "Password",
    rememberDevice: "Remember device",
    forgotPassword: "Forgot Password?",
    signInBtn: "Sign In",
    createAccountBtn: "Create Account",
    or: "OR",
    continueWithGoogle: "Continue with Google",
    continueWithApple: "Continue with Apple",
    continueWithGithub: "Continue with GitHub",
    continueWithMicrosoft: "Continue with Microsoft",
    continueWithDiscord: "Continue with Discord",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    signUpLink: "Sign Up",
    signInLink: "Sign In",
    soon: "Soon",
    protectedBySecurity: "Protected by SoftView Security",
    protectedByDesc: "Industry-leading account encryption",
    e2eEncryption: "End-to-End Encryption",
    passkeysReady: "Passkeys Ready",
    aiThreatProtection: "AI Threat Protection",
    twoFactorAuth: "2FA Security",
  },
  uz: {
    watchSmarter1: "Aqlliroq ",
    watchSmarter2: "Ko‘ring.",
    learnFaster1: "Tezroq ",
    learnFaster2: "O‘rganing.",
    subtitle: "Ajoyib videolar, jonli efirlar va kurslarni kashf eting. AI kuchi bilan shaxsiylashtirilgan.",
    aiRec: "AI Tavsiyasi",
    basedOnHistory: "Tomosha tarixi asosida",
    continueLearning: "O‘rganishni davom ettiring",
    yourProgress: "Sizning natijangiz",
    thisWeek: "Bu hafta",
    streak: "Ketma-ketlik",
    keepItUp: "Barakalla!",
    days: "Kun",
    protectedDataTitle: "Xavfsiz Ma’lumotlar",
    protectedDataDesc: "Ma’lumotlaringiz doim himoyalangan",
    smartSuggestionsTitle: "Aqlli Tavsiyalar",
    smartSuggestionsDesc: "Siz uchun AI tavsiyalari",
    anyDeviceTitle: "Har Qanday Qurilma",
    anyDeviceDesc: "Istalgan qurilmadan kiring",
    welcomeBack: "Xush Kelibsiz 👋",
    createAccountHeader: "Hisob Yaratish 🚀",
    signInSub: "SoftView-dan foydalanish uchun hisobingizga kiring",
    signUpSub: "SoftView sayohatini boshlash uchun ro‘yxatdan o‘ting",
    fullName: "To‘liq Ismingiz",
    emailOrUsername: "Email yoki Foydalanuvchi nomi",
    password: "Parol",
    rememberDevice: "Qurilmani eslab qolish",
    forgotPassword: "Parolni unutdingizmi?",
    signInBtn: "Tizimga Kirish",
    createAccountBtn: "Hisob Yaratish",
    or: "YOKI",
    continueWithGoogle: "Google orqali kirish",
    continueWithApple: "Apple orqali kirish",
    continueWithGithub: "GitHub orqali kirish",
    continueWithMicrosoft: "Microsoft orqali kirish",
    continueWithDiscord: "Discord orqali kirish",
    dontHaveAccount: "Hisobingiz yo‘qmi?",
    alreadyHaveAccount: "Hisobingiz bormi?",
    signUpLink: "Ro‘yxatdan o‘tish",
    signInLink: "Tizimga kirish",
    soon: "Tez kunda",
    protectedBySecurity: "SoftView Xavfsizligi Himoyasida",
    protectedByDesc: "Yuqori darajadagi ma’lumotlar shifrlanishi",
    e2eEncryption: "End-to-End Shifrlash",
    passkeysReady: "Passkey Tayyor",
    aiThreatProtection: "AI Xavfsizlik Himoyasi",
    twoFactorAuth: "2FA Xavfsizlik",
  },
  ru: {
    watchSmarter1: "Смотрите ",
    watchSmarter2: "Умнее.",
    learnFaster1: "Учитесь ",
    learnFaster2: "Быстрее.",
    subtitle: "Открывайте видео, трансляции и курсы. Персонализировано с помощью ИИ.",
    aiRec: "ИИ Рекомендация",
    basedOnHistory: "На основе истории просмотра",
    continueLearning: "Продолжить обучение",
    yourProgress: "Ваш прогресс",
    thisWeek: "На этой неделе",
    streak: "Серия",
    keepItUp: "Так держать!",
    days: "Дней",
    protectedDataTitle: "Защищенные данные",
    protectedDataDesc: "Ваши данные всегда под защитой",
    smartSuggestionsTitle: "Умные советы",
    smartSuggestionsDesc: "Персональные ИИ рекомендации",
    anyDeviceTitle: "Любое устройство",
    anyDeviceDesc: "Доступ с любого устройства",
    welcomeBack: "С возвращением 👋",
    createAccountHeader: "Создать аккаунт 🚀",
    signInSub: "Войдите, чтобы продолжить работу в SoftView",
    signUpSub: "Зарегистрируйтесь, чтобы начать путешествие с SoftView",
    fullName: "Полное имя",
    emailOrUsername: "Email или логин",
    password: "Пароль",
    rememberDevice: "Запомнить устройство",
    forgotPassword: "Забыли пароль?",
    signInBtn: "Войти",
    createAccountBtn: "Создать аккаунт",
    or: "ИЛИ",
    continueWithGoogle: "Продолжить с Google",
    continueWithApple: "Продолжить с Apple",
    continueWithGithub: "Продолжить с GitHub",
    continueWithMicrosoft: "Продолжить с Microsoft",
    continueWithDiscord: "Продолжить с Discord",
    dontHaveAccount: "Нет аккаунта?",
    alreadyHaveAccount: "Уже есть аккаунт?",
    signUpLink: "Регистрация",
    signInLink: "Войти",
    soon: "Скоро",
    protectedBySecurity: "Защищено SoftView Security",
    protectedByDesc: "Передовое шифрование аккаунта",
    e2eEncryption: "Сквозное шифрование",
    passkeysReady: "Поддержка Passkey",
    aiThreatProtection: "ИИ защита от угроз",
    twoFactorAuth: "2FA Безопасность",
  },
  es: {
    watchSmarter1: "Mira con ",
    watchSmarter2: "Inteligencia.",
    learnFaster1: "Aprende más ",
    learnFaster2: "Rápido.",
    subtitle: "Descubre videos, transmisiones en vivo y cursos. Personalizado con el poder de la IA.",
    aiRec: "Recomendación IA",
    basedOnHistory: "Basado en tu historial",
    continueLearning: "Continuar aprendiendo",
    yourProgress: "Tu Progreso",
    thisWeek: "Esta Semana",
    streak: "Racha",
    keepItUp: "¡Sigue así!",
    days: "Días",
    protectedDataTitle: "Datos Protegidos",
    protectedDataDesc: "Tus datos siempre seguros",
    smartSuggestionsTitle: "Sugerencias IA",
    smartSuggestionsDesc: "Recomendaciones personalizadas",
    anyDeviceTitle: "Cualquier Dispositivo",
    anyDeviceDesc: "Accede desde cualquier lugar",
    welcomeBack: "Bienvenido de nuevo 👋",
    createAccountHeader: "Crear Cuenta 🚀",
    signInSub: "Inicia sesión para continuar en SoftView",
    signUpSub: "Regístrate para comenzar tu viaje en SoftView",
    fullName: "Nombre Completo",
    emailOrUsername: "Correo o Usuario",
    password: "Contraseña",
    rememberDevice: "Recordar dispositivo",
    forgotPassword: "¿Olvidaste tu contraseña?",
    signInBtn: "Iniciar Sesión",
    createAccountBtn: "Crear Cuenta",
    or: "O",
    continueWithGoogle: "Continuar con Google",
    continueWithApple: "Continuar con Apple",
    continueWithGithub: "Continuar con GitHub",
    continueWithMicrosoft: "Continuar con Microsoft",
    continueWithDiscord: "Continuar con Discord",
    dontHaveAccount: "¿No tienes una cuenta?",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    signUpLink: "Registrarse",
    signInLink: "Iniciar Sesión",
    soon: "Pronto",
    protectedBySecurity: "Protegido por SoftView Security",
    protectedByDesc: "Cifrado de cuenta de alto nivel",
    e2eEncryption: "Cifrado de extremo a extremo",
    passkeysReady: "Listo para Passkeys",
    aiThreatProtection: "Protección contra amenazas IA",
    twoFactorAuth: "Seguridad 2FA",
  },
  de: {
    watchSmarter1: "Smarter ",
    watchSmarter2: "Zuschauen.",
    learnFaster1: "Schneller ",
    learnFaster2: "Lernen.",
    subtitle: "Entdecke tolle Videos, Livestreams und Kurse. Personalisiert durch die Kraft der KI.",
    aiRec: "KI-Empfehlung",
    basedOnHistory: "Basiert auf Verlauf",
    continueLearning: "Weiterlernen",
    yourProgress: "Dein Fortschritt",
    thisWeek: "Diese Woche",
    streak: "Serie",
    keepItUp: "Weiter so!",
    days: "Tage",
    protectedDataTitle: "Geschützte Daten",
    protectedDataDesc: "Deine Daten sind immer geschützt",
    smartSuggestionsTitle: "Smarte Vorschläge",
    smartSuggestionsDesc: "Smarte KI Empfehlungen für dich",
    anyDeviceTitle: "Jedes Gerät",
    anyDeviceDesc: "Zugriff von allen Geräten",
    welcomeBack: "Willkommen zurück 👋",
    createAccountHeader: "Konto Erstellen 🚀",
    signInSub: "Melde dich an, um mit SoftView fortzufahren",
    signUpSub: "Registriere dich, um deine SoftView Reise zu starten",
    fullName: "Vollständiger Name",
    emailOrUsername: "E-Mail oder Benutzername",
    password: "Passwort",
    rememberDevice: "Gerät merken",
    forgotPassword: "Passwort vergessen?",
    signInBtn: "Anmelden",
    createAccountBtn: "Konto Erstellen",
    or: "ODER",
    continueWithGoogle: "Weiter mit Google",
    continueWithApple: "Weiter mit Apple",
    continueWithGithub: "Weiter mit GitHub",
    continueWithMicrosoft: "Weiter mit Microsoft",
    continueWithDiscord: "Weiter mit Discord",
    dontHaveAccount: "Noch kein Konto?",
    alreadyHaveAccount: "Bereits ein Konto?",
    signUpLink: "Registrieren",
    signInLink: "Anmelden",
    soon: "Demnächst",
    protectedBySecurity: "Geschützt durch SoftView Security",
    protectedByDesc: "Branchenführende Kontoverschlüsselung",
    e2eEncryption: "Ende-zu-Ende Verschlüsselung",
    passkeysReady: "Passkey-Bereit",
    aiThreatProtection: "KI-Bedrohungsschutz",
    twoFactorAuth: "2FA Sicherheit",
  }
};
